/* 文综冲刺题库 — 自编，覆盖中考"社会·法治"客观题高频考点与诱错点。
   加题/改题只改本文件，不动 app.js 逻辑。
   字段：id, subject, type(judge判断/single单选/multi组合多选),
        stem题干, options选项, answer答案(T/F | "A" | ["A","C"]),
        why一句话解析, trap诱错点(可空), beast失分机制, source, difficulty(1-3) */

window.QUESTIONS = [
  /* ================= 中国史（最弱，重点） ================= */
  { id:"ZGS-01", subject:"中国史", type:"judge", stem:"元谋人是我国境内目前已知最早的人类。", options:[], answer:"T",
    why:"元谋人距今约170万年，是我国境内目前已知最早的人类。", trap:null, beast:"知识怪", source:"自编·02速记", difficulty:1 },
  { id:"ZGS-02", subject:"中国史", type:"judge", stem:"河姆渡遗址位于陕西，居民主要种植粟。", options:[], answer:"F",
    why:"河姆渡在浙江余姚（长江流域）种水稻；种粟、住半地穴、有人面鱼纹盆的是陕西半坡。", trap:"张冠李戴", beast:"知识怪", source:"自编·真题诱错", difficulty:2 },
  { id:"ZGS-03", subject:"中国史", type:"single", stem:"人面鱼纹彩陶盆出土于下列哪一遗址？", options:["河姆渡遗址","半坡遗址","良渚古城","二里头遗址"], answer:"B",
    why:"人面鱼纹彩陶盆是黄河流域半坡遗址的典型文物。", trap:null, beast:"知识怪", source:"自编·02速记", difficulty:2 },
  { id:"ZGS-04", subject:"中国史", type:"single", stem:"我国历史上第一个王朝是？", options:["商朝","夏朝","西周","秦朝"], answer:"B",
    why:"约公元前2070年禹建立夏朝，是我国第一个王朝。", trap:null, beast:"知识怪", source:"自编·02速记", difficulty:1 },
  { id:"ZGS-05", subject:"中国史", type:"single", stem:"“封建亲戚，以蕃屏周”描述的西周政治制度是？", options:["禅让制","分封制","郡县制","行省制"], answer:"B",
    why:"西周实行分封制，封邦建国以拱卫周王室。", trap:null, beast:"审题怪", source:"自编·02速记", difficulty:2 },
  { id:"ZGS-06", subject:"中国史", type:"single", stem:"秦朝在地方上推行、对后世影响深远的制度是？", options:["分封制","郡县制","行省制","三省六部制"], answer:"B",
    why:"秦朝废分封、行郡县，开创中央集权下的地方行政制度。", trap:null, beast:"知识怪", source:"自编·02速记", difficulty:1 },
  { id:"ZGS-07", subject:"中国史", type:"judge", stem:"科举制创立于唐朝，在清朝末年被废除。", options:[], answer:"F",
    why:"科举制创立于隋朝（隋炀帝设进士科），清末1905年废除——创立朝代记错。", trap:"时间线混淆", beast:"知识怪", source:"自编·02速记", difficulty:2 },
  { id:"ZGS-08", subject:"中国史", type:"single", stem:"“尽道隋亡为此河，至今千里赖通波”歌咏的是？", options:["长城","大运河","灵渠","都江堰"], answer:"B",
    why:"诗句指隋朝大运河，沟通南北、便利漕运。", trap:null, beast:"审题怪", source:"自编·02速记", difficulty:2 },
  { id:"ZGS-09", subject:"中国史", type:"single", stem:"北魏孝文帝改革（迁都洛阳、说汉语、改汉姓）的主要影响是？", options:["结束分裂","促进民族交融","开创科举","加强海防"], answer:"B",
    why:"孝文帝改革促进了民族交融，增强中华民族共同体意识。", trap:null, beast:"知识怪", source:"自编·真题", difficulty:2 },
  { id:"ZGS-10", subject:"中国史", type:"judge", stem:"行省制度创立于元朝，是我国省级行政区划的开端。", options:[], answer:"T",
    why:"元朝设行中书省管理地方，是我国省制的开端。", trap:null, beast:"知识怪", source:"自编·02速记", difficulty:2 },
  { id:"ZGS-11", subject:"中国史", type:"single", stem:"元朝管理西藏地区的中央机构是？", options:["宣政院","澎湖巡检司","驻藏大臣","伊犁将军"], answer:"A",
    why:"元朝设宣政院管理西藏；澎湖巡检司管的是台湾（澎湖、琉球）。", trap:"张冠李戴", beast:"知识怪", source:"自编·真题诱错", difficulty:3 },
  { id:"ZGS-12", subject:"中国史", type:"single", stem:"清朝1727年设置、加强对西藏管辖的官职是？", options:["宣政院","驻藏大臣","伊犁将军","台湾府"], answer:"B",
    why:"1727年清朝设驻藏大臣，代表中央政府监督西藏事务。", trap:null, beast:"知识怪", source:"自编·02速记", difficulty:2 },
  { id:"ZGS-13", subject:"中国史", type:"judge", stem:"张骞出使西域，开辟了“海上丝绸之路”。", options:[], answer:"F",
    why:"张骞通西域开辟的是陆上丝绸之路；走海路的是郑和下西洋。", trap:"张冠李戴", beast:"知识怪", source:"自编·真题诱错", difficulty:2 },
  { id:"ZGS-14", subject:"中国史", type:"single", stem:"标志着中国近代史开端的事件是？", options:["第二次鸦片战争","鸦片战争","甲午中日战争","八国联军侵华"], answer:"B",
    why:"1840年鸦片战争使中国开始沦为半殖民地半封建社会，是中国近代史的开端。", trap:null, beast:"知识怪", source:"自编·02速记", difficulty:1 },
  { id:"ZGS-15", subject:"中国史", type:"single", stem:"洋务运动前期、后期分别以什么为口号？", options:["自强、求富","扶清灭洋","民主、科学","实业救国"], answer:"A",
    why:"洋务派以“自强”“求富”为口号，创办近代军事、民用工业。", trap:null, beast:"知识怪", source:"自编·真题", difficulty:2 },
  { id:"ZGS-16", subject:"中国史", type:"judge", stem:"戊戌变法使中国走上了资本主义发展道路。", options:[], answer:"F",
    why:"戊戌变法很快失败，没有改变中国半殖民地半封建社会的性质。", trap:"说法太绝对", beast:"知识怪", source:"自编·真题诱错", difficulty:2 },
  { id:"ZGS-17", subject:"中国史", type:"single", stem:"中国近代化探索的正确先后顺序是？", options:["洋务运动→戊戌变法→辛亥革命→新文化运动","戊戌变法→洋务运动→辛亥革命→新文化运动","辛亥革命→洋务运动→戊戌变法→新文化运动","洋务运动→辛亥革命→戊戌变法→新文化运动"], answer:"A",
    why:"由器物（洋务）→制度（戊戌、辛亥）→思想（新文化），层层深入。", trap:"时间线混淆", beast:"审题怪", source:"自编·02速记", difficulty:2 },
  { id:"ZGS-18", subject:"中国史", type:"single", stem:"新文化运动高举的两面大旗是？", options:["自强与求富","民主与科学","三民主义","实业救国"], answer:"B",
    why:"新文化运动提倡“民主”（德先生）与“科学”（赛先生）。", trap:null, beast:"知识怪", source:"自编·02速记", difficulty:1 },
  { id:"ZGS-19", subject:"中国史", type:"judge", stem:"五四运动是中国新民主主义革命的开端。", options:[], answer:"T",
    why:"1919年五四运动中无产阶级登上历史舞台，是新民主主义革命的开端。", trap:null, beast:"知识怪", source:"自编·真题", difficulty:2 },
  { id:"ZGS-20", subject:"中国史", type:"single", stem:"中国共产党成立于哪一年？", options:["1919年","1921年","1924年","1927年"], answer:"B",
    why:"1921年中共一大召开，标志着中国共产党成立。", trap:null, beast:"知识怪", source:"自编·02速记", difficulty:1 },
  { id:"ZGS-21", subject:"中国史", type:"single", stem:"打响武装反抗国民党反动统治第一枪的事件是？", options:["南昌起义","秋收起义","井冈山会师","武昌起义"], answer:"A",
    why:"1927年8月1日南昌起义，打响了武装反抗国民党反动派的第一枪。", trap:null, beast:"知识怪", source:"自编·02速记", difficulty:2 },
  { id:"ZGS-22", subject:"中国史", type:"single", stem:"毛泽东在井冈山开辟的中国革命正确道路是？", options:["城市中心论","农村包围城市、武装夺取政权","和平过渡","工人罢工"], answer:"B",
    why:"“农村包围城市、武装夺取政权”的井冈山道路符合中国国情。", trap:null, beast:"知识怪", source:"自编·真题", difficulty:2 },
  { id:"ZGS-23", subject:"中国史", type:"single", stem:"中国十四年抗战开始的标志是？", options:["九一八事变","七七事变","西安事变","南京大屠杀"], answer:"A",
    why:"1931年九一八事变，中国局部抗战开始（十四年抗战起点）；七七事变是全民族抗战开始，别混。", trap:"审题怪", beast:"审题怪", source:"自编·真题诱错", difficulty:3 },
  { id:"ZGS-24", subject:"中国史", type:"judge", stem:"1956年底三大改造基本完成，标志着社会主义基本制度在我国建立起来。", options:[], answer:"T",
    why:"三大改造完成、公有制确立，社会主义基本制度建立，我国进入社会主义初级阶段。", trap:null, beast:"知识怪", source:"自编·真题", difficulty:2 },
  { id:"ZGS-25", subject:"中国史", type:"single", stem:"我国改革开放和社会主义现代化建设新时期的开端是？", options:["中共八大","十一届三中全会","南方谈话","中共十八大"], answer:"B",
    why:"1978年十一届三中全会作出改革开放的伟大决策，是新时期的开端。", trap:null, beast:"知识怪", source:"自编·真题", difficulty:2 },

  /* ================= 道法 ================= */
  { id:"DF-01", subject:"道法", type:"judge", stem:"犯罪最本质的特征是严重社会危害性。", options:[], answer:"T",
    why:"犯罪三特征：严重社会危害性（最本质）、刑事违法性、应受刑罚处罚性。", trap:null, beast:"知识怪", source:"自编·05速记", difficulty:2 },
  { id:"DF-02", subject:"道法", type:"single", stem:"区分一般违法行为与犯罪的根本标准是？", options:["是否违反了法律","社会危害程度是否严重","是否被起诉","是否出于故意"], answer:"B",
    why:"社会危害程度是否严重（是否触犯刑法、应否受刑罚）是犯罪与一般违法的根本区别。", trap:null, beast:"知识怪", source:"自编·05速记", difficulty:2 },
  { id:"DF-03", subject:"道法", type:"judge", stem:"拾得他人遗失物拒不归还，属于行政违法行为。", options:[], answer:"F",
    why:"这侵犯他人财产权、属不当得利，是民事违法行为，应承担民事责任。", trap:"原理误用", beast:"知识怪", source:"自编·真题诱错", difficulty:3 },
  { id:"DF-04", subject:"道法", type:"single", stem:"下列属于刑事违法行为（犯罪）的是？", options:["欠钱不还","闯红灯","持械抢劫他人财物","乱扔垃圾"], answer:"C",
    why:"抢劫具有严重社会危害性、触犯刑法，属犯罪；其余分别是民事、行政违法。", trap:null, beast:"知识怪", source:"自编·05速记", difficulty:2 },
  { id:"DF-05", subject:"道法", type:"judge", stem:"我国宪法是国家的根本大法，具有最高的法律效力。", options:[], answer:"T",
    why:"宪法规定国家根本制度和根本任务，是其他法律的立法基础，具有最高法律效力。", trap:null, beast:"知识怪", source:"自编·05速记", difficulty:1 },
  { id:"DF-06", subject:"道法", type:"judge", stem:"普通法律是宪法的立法基础和立法依据。", options:[], answer:"F",
    why:"恰恰相反：宪法是普通法律的立法基础，普通法律是宪法的具体化。", trap:"因果倒置", beast:"知识怪", source:"自编·真题诱错", difficulty:3 },
  { id:"DF-07", subject:"道法", type:"single", stem:"我国的根本政治制度是？", options:["人民代表大会制度","政治协商制度","民族区域自治制度","基层群众自治制度"], answer:"A",
    why:"人民代表大会制度是我国的根本政治制度。", trap:null, beast:"知识怪", source:"自编·05速记", difficulty:2 },
  { id:"DF-08", subject:"道法", type:"single", stem:"我国的根本制度是？", options:["人民代表大会制度","社会主义制度","公有制","按劳分配"], answer:"B",
    why:"社会主义制度是我国的根本制度，注意与“根本政治制度（人大制度）”区分。", trap:"偷换概念", beast:"知识怪", source:"自编·真题诱错", difficulty:3 },
  { id:"DF-09", subject:"道法", type:"judge", stem:"公民可以只享受权利而不履行义务。", options:[], answer:"F",
    why:"权利与义务相统一，公民既享有权利又必须履行义务。", trap:"说法太绝对", beast:"知识怪", source:"自编·05速记", difficulty:1 },
  { id:"DF-10", subject:"道法", type:"single", stem:"“有事好商量，众人的事情由众人商量”，全过程人民民主最本质的体现是？", options:["人民当家作主","对外开放","民主集中","依法治国"], answer:"A",
    why:"全过程人民民主体现人民当家作主，最广泛、最真实、最管用。", trap:null, beast:"知识怪", source:"自编·真题", difficulty:2 },
  { id:"DF-11", subject:"道法", type:"judge", stem:"民族区域自治地方可以行使高度自治权。", options:[], answer:"F",
    why:"民族区域自治不等于“高度自治”；“高度自治权”是特别行政区（一国两制）的特点。", trap:"偷换概念", beast:"知识怪", source:"自编·真题诱错", difficulty:3 },
  { id:"DF-12", subject:"道法", type:"judge", stem:"维护国家安全只是国家机关和军队的事，与普通公民无关。", options:[], answer:"F",
    why:"维护国家安全是每个公民的义务，国家安全人人有责。", trap:"说法太绝对", beast:"知识怪", source:"自编·真题诱错", difficulty:2 },
  { id:"DF-13", subject:"道法", type:"single", stem:"我国处理民族关系的基本原则是？", options:["民族平等、团结、共同繁荣","民族自决","高度自治","一国两制"], answer:"A",
    why:"坚持民族平等、民族团结、各民族共同繁荣的基本原则。", trap:null, beast:"知识怪", source:"自编·05速记", difficulty:2 },
  { id:"DF-14", subject:"道法", type:"single", stem:"解决我国一切问题的基础和关键是？", options:["创新","发展","教育","开放"], answer:"B",
    why:"发展是党执政兴国的第一要务，是解决我国一切问题的基础和关键。", trap:"偷换概念", beast:"知识怪", source:"自编·真题诱错", difficulty:2 },
  { id:"DF-15", subject:"道法", type:"judge", stem:"创新是引领发展的第一动力。", options:[], answer:"T",
    why:"创新是引领发展的第一动力，是建设现代化经济体系的战略支撑。", trap:null, beast:"知识怪", source:"自编·05速记", difficulty:1 },
  { id:"DF-16", subject:"道法", type:"single", stem:"中国举办进博会、共建“一带一路”，积极推动构建？", options:["人类命运共同体","单极世界","发达国家俱乐部","世界领导地位"], answer:"A",
    why:"中国主张构建人类命运共同体；“领导世界”“主导”等是霸权语气，错误。", trap:"说法太绝对", beast:"审题怪", source:"自编·真题诱错", difficulty:2 },

  /* ================= 地理 ================= */
  { id:"DL-01", subject:"地理", type:"single", stem:"我国地势的总特征是？", options:["东高西低","西高东低，呈三级阶梯","南高北低","四周高、中间低"], answer:"B",
    why:"我国地势西高东低，呈三级阶梯状分布。", trap:null, beast:"知识怪", source:"自编·03速记", difficulty:1 },
  { id:"DL-02", subject:"地理", type:"single", stem:"我国1月0℃等温线、800mm年等降水量线大致经过？", options:["秦岭—淮河一线","大兴安岭","昆仑山","长江"], answer:"A",
    why:"秦岭—淮河是我国重要的南北方分界线（1月0℃等温线、800mm等降水量线）。", trap:null, beast:"知识怪", source:"自编·03速记", difficulty:2 },
  { id:"DL-03", subject:"地理", type:"judge", stem:"秦岭—淮河以南以旱地为主，主要种植小麦。", options:[], answer:"F",
    why:"以南是水田、种水稻；以北才是旱地、种小麦——南北弄反了。", trap:"张冠李戴", beast:"知识怪", source:"自编·真题诱错", difficulty:2 },
  { id:"DL-04", subject:"地理", type:"single", stem:"我国四大地理区域中，最突出自然特征是“干旱”的是？", options:["北方地区","南方地区","西北地区","青藏地区"], answer:"C",
    why:"西北地区深居内陆、距海远，最突出的自然特征是干旱。", trap:null, beast:"知识怪", source:"自编·03速记", difficulty:2 },
  { id:"DL-05", subject:"地理", type:"single", stem:"青藏地区最突出的自然特征是？", options:["干旱","高寒","湿热","多台风"], answer:"B",
    why:"青藏地区平均海拔最高，最突出的自然特征是高寒。", trap:null, beast:"知识怪", source:"自编·03速记", difficulty:1 },
  { id:"DL-06", subject:"地理", type:"judge", stem:"在等高线地形图上，等高线越稀疏表示坡度越陡。", options:[], answer:"F",
    why:"等高线越密集坡度越陡，越稀疏坡度越缓——读反了。", trap:"地理判读错", beast:"知识怪", source:"自编·真题诱错", difficulty:2 },
  { id:"DL-07", subject:"地理", type:"single", stem:"北京(40°N,116°E)位于哈尔滨(46°N,126°E)的什么方向？", options:["东南","西南","东北","西北"], answer:"B",
    why:"纬度低在南、经度小在西（东经越大越靠东），故北京在哈尔滨的西南方。", trap:"地理判读错", beast:"审题怪", source:"自编·真题诱错", difficulty:3 },
  { id:"DL-08", subject:"地理", type:"single", stem:"“全年温和湿润、降水均匀，多汁牧草、乳畜业发达”是哪种气候？", options:["地中海气候","温带海洋性气候","温带季风气候","热带雨林气候"], answer:"B",
    why:"温带海洋性气候（典型在欧洲西部）全年温和湿润，利于乳畜业。", trap:null, beast:"知识怪", source:"自编·03速记", difficulty:2 },
  { id:"DL-09", subject:"地理", type:"single", stem:"“夏季炎热干燥、冬季温和多雨”（雨热不同期）的气候是？", options:["亚热带季风气候","地中海气候","温带季风气候","热带草原气候"], answer:"B",
    why:"地中海气候雨热不同期（冬雨夏干），是常考的“反常识”点。", trap:null, beast:"知识怪", source:"自编·03速记", difficulty:2 },
  { id:"DL-10", subject:"地理", type:"single", stem:"被称为“三洲五海之地”、石油资源丰富、长期是世界热点的地区是？", options:["东南亚","中东","欧洲西部","南极洲"], answer:"B",
    why:"中东地处亚非欧三洲、五海之地，是石油宝库，也是矛盾热点。", trap:null, beast:"知识怪", source:"自编·03速记", difficulty:2 },
  { id:"DL-11", subject:"地理", type:"judge", stem:"长江是我国含沙量最大的河流，被称为“地上河”。", options:[], answer:"F",
    why:"含沙量最大、有“地上河”之称的是黄河（中游流经黄土高原）。", trap:"张冠李戴", beast:"知识怪", source:"自编·真题诱错", difficulty:2 },
  { id:"DL-12", subject:"地理", type:"single", stem:"判读气候类型时，确定所属“温度带”主要依据是？", options:["最热月气温","最冷月气温","年降水总量","降水的季节分配"], answer:"B",
    why:"先看最冷月气温定带（>15℃热带、0~15℃亚热带等），再看降水定型。", trap:null, beast:"知识怪", source:"自编·03速记", difficulty:2 },

  /* ================= 世界史 ================= */
  { id:"SJS-01", subject:"世界史", type:"single", stem:"古代两河流域、维护奴隶主利益的著名成文法典是？", options:["《十二铜表法》","《汉谟拉比法典》","《罗马民法大全》","《人权宣言》"], answer:"B",
    why:"《汉谟拉比法典》是古巴比伦（两河流域）现存最早的较完整成文法典。", trap:null, beast:"知识怪", source:"自编·04速记", difficulty:2 },
  { id:"SJS-02", subject:"世界史", type:"judge", stem:"《汉谟拉比法典》维护的是封建等级制度。", options:[], answer:"F",
    why:"它维护的是奴隶制度（奴隶主利益），不是封建等级制度。", trap:"偷换概念", beast:"知识怪", source:"自编·真题诱错", difficulty:2 },
  { id:"SJS-03", subject:"世界史", type:"single", stem:"古代雅典民主政治的局限性主要表现在？", options:["人人平等","妇女、奴隶和外邦人没有政治权利","全民参与","实行君主专制"], answer:"B",
    why:"雅典民主只属于成年男性公民，妇女、奴隶、外邦人被排除在外。", trap:null, beast:"知识怪", source:"自编·04速记", difficulty:2 },
  { id:"SJS-04", subject:"世界史", type:"single", stem:"为资本主义兴起奠定思想文化基础的思想解放运动是？", options:["文艺复兴","新航路开辟","工业革命","三角贸易"], answer:"A",
    why:"文艺复兴以人文主义为核心、解放思想，为资本主义兴起奠定思想文化基础。", trap:null, beast:"知识怪", source:"自编·04速记", difficulty:2 },
  { id:"SJS-05", subject:"世界史", type:"judge", stem:"文艺复兴为资本主义的产生奠定了物质基础。", options:[], answer:"F",
    why:"文艺复兴奠定的是思想文化基础（思想解放），不是物质基础。", trap:"偷换概念", beast:"知识怪", source:"自编·真题诱错", difficulty:3 },
  { id:"SJS-06", subject:"世界史", type:"single", stem:"标志着马克思主义诞生的事件是？", options:["《共产党宣言》发表","巴黎公社成立","第一国际成立","俄国十月革命"], answer:"A",
    why:"1848年《共产党宣言》发表，标志着马克思主义诞生。", trap:null, beast:"知识怪", source:"自编·04速记", difficulty:2 },
  { id:"SJS-07", subject:"世界史", type:"single", stem:"世界上第一次建立无产阶级政权的伟大尝试是？", options:["巴黎公社","十月革命","第一国际","宪章运动"], answer:"A",
    why:"1871年巴黎公社是无产阶级建立政权的第一次伟大尝试。", trap:null, beast:"知识怪", source:"自编·04速记", difficulty:2 },
  { id:"SJS-08", subject:"世界史", type:"judge", stem:"莫斯科保卫战是第二次世界大战的转折点。", options:[], answer:"F",
    why:"二战转折点是斯大林格勒战役；莫斯科保卫战粉碎了德军“闪电战”和“不可战胜”神话。", trap:"张冠李戴", beast:"知识怪", source:"自编·真题诱错", difficulty:3 },
  { id:"SJS-09", subject:"世界史", type:"single", stem:"把人类带入“蒸汽时代”的标志性发明是？", options:["瓦特改良蒸汽机","电灯","内燃机","电子计算机"], answer:"A",
    why:"瓦特改良蒸汽机的广泛使用使人类进入“蒸汽时代”。", trap:null, beast:"知识怪", source:"自编·04速记", difficulty:2 },
  { id:"SJS-10", subject:"世界史", type:"single", stem:"二战后形成的、以美苏为首两大集团对峙的世界格局是？", options:["凡尔赛—华盛顿体系","冷战（两极格局）","多极化格局","经济全球化"], answer:"B",
    why:"二战后形成美苏对峙的冷战（两极）格局。", trap:null, beast:"知识怪", source:"自编·04速记", difficulty:2 },

  /* ================= 时政 ================= */
  { id:"SZ-01", subject:"时政", type:"judge", stem:"当今世界，和平与发展是时代主题，但霸权主义、强权政治依然存在，世界并不太平。", options:[], answer:"T",
    why:"和平与发展是时代主题，但局部冲突、霸权强权仍在，符合实际。", trap:null, beast:"知识怪", source:"自编·真题", difficulty:1 },
  { id:"SZ-02", subject:"时政", type:"single", stem:"中国为解决全球问题贡献的“中国方案”是？", options:["构建人类命运共同体","结盟对抗","领导世界","闭关锁国"], answer:"A",
    why:"中国主张构建人类命运共同体，推动建设持久和平、共同繁荣的世界。", trap:null, beast:"知识怪", source:"自编·真题", difficulty:1 },
  { id:"SZ-03", subject:"时政", type:"judge", stem:"我国坚持对外开放的基本国策，实行“引进来”和“走出去”相结合。", options:[], answer:"T",
    why:"对外开放是我国的基本国策，坚持“引进来”与“走出去”相结合。", trap:null, beast:"知识怪", source:"自编·05速记", difficulty:1 },
  { id:"SZ-04", subject:"时政", type:"single", stem:"共建“一带一路”体现的是？", options:["互利共赢的开放战略","军事同盟","对外援助的沉重负担","争夺世界霸权"], answer:"A",
    why:"“一带一路”是开放包容、互利共赢的合作倡议，不是军事同盟或霸权。", trap:"说法太绝对", beast:"审题怪", source:"自编·真题诱错", difficulty:2 },
  { id:"SZ-05", subject:"时政", type:"single", stem:"实现中华民族伟大复兴的必由之路是？", options:["对外开放","中国特色社会主义道路","科技创新","对外贸易"], answer:"B",
    why:"中国特色社会主义道路是实现中华民族伟大复兴的必由之路。", trap:null, beast:"知识怪", source:"自编·05速记", difficulty:2 }
];

/* ================= 综合题（采分点自评用，也供组卷打印） ================= */
window.SUBJECTIVE = [
  { id:"ZH-DL-01", subject:"地理", category:"地理类",
    prompt:"读“我国西北地区”相关图文材料，回答：\n(1) 指出西北地区最突出的自然特征及其成因。\n(2) 分析当地发展农业的有利与不利条件。\n(3) 为西北地区可持续发展提出两条建议。",
    scorePoints:[
      "最突出特征＝干旱；成因＝深居内陆、距海远，湿润气流难以到达",
      "有利：光照充足、昼夜温差大（瓜果含糖量高）；有高山冰雪融水可发展绿洲/灌溉农业",
      "不利：降水少、水资源短缺；生态脆弱、易荒漠化",
      "建议：发展节水农业、合理利用水资源；防治荒漠化、退耕还林还草；因地制宜发展特色农业；坚持人与自然和谐共生"
    ],
    terms:["深居内陆","绿洲农业","荒漠化","因地制宜","可持续发展","人与自然和谐共生"],
    tip:"区域题套路：位置 → 自然特征(地形·气候·河流) → 区位条件(自然+社会经济) → 可持续措施。" },

  { id:"ZH-LS-01", subject:"中国史", category:"历史类",
    prompt:"围绕“中国共产党领导人民探索出符合国情的正确道路”，结合史实，论述“立足国情、实事求是”的重要性。（要求：观点明确、史论结合、逻辑清晰）",
    scorePoints:[
      "观点：一个国家走什么道路，必须立足本国国情、实事求是",
      "史实1：井冈山道路——结合中国半殖民地半封建、农民占多数的国情，走“农村包围城市、武装夺取政权”",
      "史实2：改革开放——结合中国生产力落后的国情，开辟中国特色社会主义道路",
      "反例：照搬苏联“城市中心论”使中国革命遭受挫折",
      "结论：只有把马克思主义同中国国情相结合、独立自主探索，才能成功，实现中华民族伟大复兴"
    ],
    terms:["实事求是","井冈山道路","农村包围城市","改革开放","中国特色社会主义","马克思主义中国化"],
    tip:"小论文＝观点(1句) ＋ 史实(2-3个、要具体) ＋ 结论(升华)。一定分点写。" },

  { id:"ZH-FZ-01", subject:"道法", category:"法治国情类",
    prompt:"材料：某地开展“宪法宣传周”活动，并对一起子女拒不履行赡养义务的案件依法判决。运用所学回答：\n(1) 宪法在我国法律体系中处于什么地位？\n(2) 为什么说“权利与义务相统一”？\n(3) 青少年应如何增强法治意识？",
    scorePoints:[
      "宪法地位：是国家的根本大法，规定国家根本制度和根本任务，具有最高法律效力，是其他法律的立法基础",
      "权利义务相统一：公民既是权利的享有者又是义务的承担者；二者相互依存、相互促进；没有无义务的权利，也没有无权利的义务",
      "青少年：学习宪法和法律知识、树立宪法意识/法治观念；依法行使权利、自觉履行义务；依法维权，同违法行为作斗争"
    ],
    terms:["根本大法","最高法律效力","立法基础","权利与义务相统一","法治意识","依法办事"],
    tip:"法治国情题套路：是什么(地位/原理) → 为什么(意义) → 怎么做(分国家/社会/青少年等主体)。" },

  { id:"ZH-SZ-01", subject:"时政", category:"时政类",
    prompt:"材料：中国连续举办进博会，高质量共建“一带一路”，提出全球发展倡议。运用所学，谈谈中国为世界发展贡献中国智慧、中国方案的意义。",
    scorePoints:[
      "推动构建人类命运共同体，建设持久和平、共同繁荣的世界",
      "践行互利共赢的开放战略，促进中国与各国合作共赢、共同发展",
      "提升中国的国际影响力，彰显负责任大国的担当",
      "推动经济全球化朝着更加开放、包容、普惠、平衡、共赢的方向发展"
    ],
    terms:["人类命运共同体","互利共赢","开放战略","大国担当","经济全球化","合作共赢"],
    tip:"意义类套路：有利于…／促进…／增强…／推动…／维护…（多角度：对中国、对世界、对人民）。" }
];
